### ISSUE TITLE
Ability - Hover Modal 

### ISSUE THREAD

**Issue by ddemuyt** [andyaiken/forgesteel#12]
### Description
Information modal on-hover over abilities

### Problem/Use Case
Informative UX/UI improvement

### Proposed Solution
Add modal when an element is hovered to display the ability/feature's information

### Additional Context
![Screenshot 2024-09-25 at 1 03 59 PM](https://github.com/user-attachments/assets/2dae0477-9327-4712-9cff-473e4802559d)

**Comment by andyaiken** [comment]
Will not work on iPads.
