### ISSUE TITLE
In-app GitHub Link

### ISSUE THREAD

**Issue by mgstreak** [andyaiken/forgesteel#24]
**Is your feature request related to a problem? Please describe.**
It would be great if in the “About” page, there was a direct link to this GitHub for visibility and to help build the community around the project. 

**Describe alternatives you've considered**
If not a separate link, then perhaps the “this project is made by Andy Aiken” could link here instead of to their personal email… I’m sure they don’t want to get messages from dunces who can’t find the repo. (To be clear… I am that dunce.)

**Additional context**
This project rules. Thanks!

**Comment by andyaiken** [comment]
Sounds entirely reasonable.
