### ISSUE TITLE
Add Ability to level up

### ISSUE THREAD

**Issue by Vospire** [andyaiken/forgesteel#28]
**Is your feature request related to a problem? Please describe.**
Characters need to be able to level up. There doesn't seem to be an automatic or manual way to progress past level 1. 

**Describe the solution you'd like**
There is a Standard advancement track:
XP 0-9 = Level 1
XP 10-24 = Level 2
XP 25-39 = Level 3
XP 40-54 = Level 4
XP 55-69 = Level 5
XP 70-84 = Level 6
XP 85-99 = Level 7
XP 100-114 = Level 8
XP 115-129 = Level 9
XP 130+ = Level 10

When the Respite is taken that pushes a character over the threshold, advance the level and indicate a level up so players can pick any new abilities available.

Also make the level manually adjustable to allow new characters to join in at a higher level.

**Describe alternatives you've considered**
Make the Level manually adjustable only.

**Additional context**

**Comment by andyaiken** [comment]
Added, but no classes or subclasses currently have data past level 1.

**Comment by Vospire** [comment]
They added a bunch of stuff in the Patreon Packet #3 at the end of October. Guess you're not getting those?
    On Sunday, November 24, 2024 at 09:14:51 AM EST, Andy Aiken ***@***.***> wrote:  
 
 


Added, but no classes or subclasses currently have data past level 1.

**Comment by andyaiken** [comment]
Patreon packet 3 isn't covered by the licence.

**Comment by Vospire** [comment]
Ah understood
    On Monday, November 25, 2024 at 07:36:18 AM EST, Andy Aiken ***@***.***> wrote:  
 
 


Patreon packet 3 isn't covered by the licence.
